-- MyRobloxUI - 自動生成UIコード
-- Generated by Roblox UI Designer

local Players = game:GetService("Players")
local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

-- ScreenGui作成
local screenGui = Instance.new("ScreenGui")
screenGui.Name = "MyRobloxUI"
screenGui.ResetOnSpawn = false
screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
screenGui.Parent = playerGui

-- タブ1
local タブ1 = Instance.new("Frame")
タブ1.Name = "タブ1"
タブ1.Size = UDim2.new(0, 200, 0, 200)
タブ1.Position = UDim2.new(0.5, 0, 0.5, 0)
タブ1.AnchorPoint = Vector2.new(0.5, 0.5)
タブ1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
タブ1.BorderSizePixel = 0
タブ1.Visible = true
タブ1.Parent = screenGui

-- タブ2
local タブ2 = Instance.new("Frame")
タブ2.Name = "タブ2"
タブ2.Size = UDim2.new(0, 200, 0, 200)
タブ2.Position = UDim2.new(0.5, 0, 0.5, 0)
タブ2.AnchorPoint = Vector2.new(0.5, 0.5)
タブ2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
タブ2.BorderSizePixel = 0
タブ2.Visible = true
タブ2.Parent = screenGui

-- １
local １ = Instance.new("TextBox")
１.Name = "１"
１.Size = UDim2.new(0, 200, 0, 50)
１.Position = UDim2.new(0.5, 0, 0.5, 0)
１.AnchorPoint = Vector2.new(0.5, 0.5)
１.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
１.PlaceholderText = "Enter text..."
１.Text = ""
１.TextColor3 = Color3.fromRGB(0, 0, 0)
１.TextSize = 18
１.Parent = screenGui

-- 2
local 2 = Instance.new("TextBox")
2.Name = "2"
2.Size = UDim2.new(0, 200, 0, 50)
2.Position = UDim2.new(0.5, 0, 0.5, 0)
2.AnchorPoint = Vector2.new(0.5, 0.5)
2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
2.PlaceholderText = "Enter text..."
2.Text = ""
2.TextColor3 = Color3.fromRGB(0, 0, 0)
2.TextSize = 18
2.Parent = screenGui

-- 3
local 3 = Instance.new("ImageLabel")
3.Name = "3"
3.Size = UDim2.new(0, 200, 0, 200)
3.Position = UDim2.new(0.5, 0, 0.5, 0)
3.AnchorPoint = Vector2.new(0.5, 0.5)
3.BackgroundTransparency = 1
3.Image = "rbxassetid://0"
3.Parent = screenGui

-- 4
local 4 = Instance.new("ImageLabel")
4.Name = "4"
4.Size = UDim2.new(0, 200, 0, 200)
4.Position = UDim2.new(0.5, 0, 0.5, 0)
4.AnchorPoint = Vector2.new(0.5, 0.5)
4.BackgroundTransparency = 1
4.Image = "rbxassetid://0"
4.Parent = screenGui

-- No.1
local No.1 = Instance.new("TextButton")
No.1.Name = "No.1"
No.1.Size = UDim2.new(0, 200, 0, 50)
No.1.Position = UDim2.new(0.5, 0, 0.5, 0)
No.1.AnchorPoint = Vector2.new(0.5, 0.5)
No.1.BackgroundColor3 = Color3.fromRGB(100, 200, 255)
No.1.Text = "Click Me"
No.1.TextColor3 = Color3.fromRGB(255, 255, 255)
No.1.TextSize = 18
No.1.Font = Enum.Font.GothamBold
No.1.Parent = screenGui

print("MyRobloxUI loaded successfully!")
